info:
  contact: {}
  license: {}
paths:
  /api/v1/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: register a new user and secret password
      parameters:
      - description: register phone code
        in: formData
        name: phone
        required: true
        type: integer
      - description: register password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Register a new user
swagger: "2.0"
